# File: backend/utils/error_handling/__init__.py

from .error_handling import (
    handle_database_error,
    handle_error_with_logging,
    handle_general_error,
    handle_authentication_error,
    handle_unauthorized_error,
    handle_route_error,
    handle_http_error,
    handle_health_check_error,
    handle_image_error,
    handle_file_handler_error,
    handle_security_error,
    handle_validation_error,
    ErrorContext,
)
from .exceptions import (
    DatabaseConnectionError,
    SchemaCreationError,
    SessionCommitError,
    LogNotFoundError,
    GeneralError,
    HealthCheckError,
    ImageError,
    FileHandlerError,
    SecurityError,
    AuthenticationError,
    AuthorizationError,
    ValidationError,
    AnalyticsError,
)

__all__ = [
    "handle_database_error",
    "handle_error_with_logging",
    "handle_general_error",
    "handle_authentication_error",
    "handle_unauthorized_error",
    "handle_route_error",
    "handle_http_error",
    "handle_health_check_error",
    "handle_image_error",
    "handle_file_handler_error",
    "handle_security_error",
    "handle_validation_error",
    "ErrorContext",
    "DatabaseConnectionError",
    "SchemaCreationError",
    "SessionCommitError",
    "LogNotFoundError",
    "GeneralError",
    "HealthCheckError",
    "ImageError",
    "FileHandlerError",
    "SecurityError",
    "AuthenticationError",
    "AuthorizationError",
    "ValidationError",
    "AnalyticsError",
]
